/* kana.h - Pengu katakana codes and strings.
 * GENERATED by tools/mkart.py - do not hand edit.
 *
 * Kana tile IDs sit above the signed char range, so these are
 * u8 arrays terminated by 0 and printed with print_kana(),
 * never PrintString().
 */
#ifndef KANA_H
#define KANA_H

#include "game.h"

#define K_SU   209
#define K_ZU   210
#define K_TA   211
#define K_BAR  212
#define K_TO   213
#define K_GE   214
#define K_MU   215
#define K_O    216
#define K_BA   217
#define K_PO   218
#define K_HA   219
#define K_I    220
#define K_KO   221
#define K_A    222
#define K_TE   223
#define K_JI   224
#define K_KU   225
#define K_GU   226
#define K_RI   227
#define K_RA   228
#define K_FU   229

extern const u8 s_clear[4];
extern const u8 s_gameover[8];
extern const u8 s_hiscore[6];
extern const u8 s_life[4];
extern const u8 s_pause[4];
extern const u8 s_stage[5];
extern const u8 s_start[5];

void print_kana(u8 plane, u8 pal, u8 x, u8 y, const u8 *codes);

#endif
